- .vscode/settings.json
- styles.css
i add responsiveness to the page
> add responsiveness to the page

- forum.html
- index.html
- jobs.html
- scholarships.html
- styles.css
Added the footer section with all the alignment , beautification and also responsiveness with icons.
Hope you liked the Footer!!
I would be grateful if you merge my Pull Request.
> Added the Footer Section with Icons and Responsiveness

- forum.html
- index.html
- jobs.html
- scholarships.html
- styles.css
> Devx mani < added pathsphere as a home navigation >

- styles.css
> DevxMani issue #32 done

- index.html
- script.js
fixes #36 
https://github.com/user-attachments/assets/cd5115da-91da-414e-bd63-8a3d20d5379d
> added gsap to enhance the home page

- contributing.md
- faqs.html
- forum.html
- jobs.html
- scholarships.html
- styles.css
added FAQS on the page 
https://github.com/user-attachments/assets/6ba5bfa9-e6a0-493b-a3ec-735e116ac55c
> Add more section to make it more attractive #5

- forum.html
- styles.css
I have added the forum page pls check it
Also pls add the hacktoberfest label 
Thank you
> added forum page

- jobs.html
- scholarships.html
This pull request includes significant improvements to the scholarship and job sections of the PathSphere project.
- #2  , level2  ,  GSSoC-Extended , Hacktoberfest
- **Scholarship Section**:
- Added detailed listings for various scholarships.
- Implemented a search functionality to filter scholarships based on user input.
- Included an "Apply Now" button for each scholarship, which triggers a confirmation pop-up.
- **Job Section**:
- Added detailed job listings for various positions.
- Implemented a search functionality to filter jobs based on keywords.
- Included an "Apply Now" button for each job, which triggers a confirmation pop-up.
> Improve scholarship and job sections with enhanced features

- blog.html
- faqs.html
- forum.html
- index.html
- jobs.html
- scholarships.html
- script.js
- styles.css
Added dark mode to all the pages like scholarship,jobs,forum,fyqs pages
> Added dark mode to all the pages(issue #66)

- index.html
- styles.css
Hero Section of Website Homepage is updated.
> Hero Section of Homepage Updated

- script.js
- styles.css
Added relevant fonts and styling to FAQs section and made it more appealing
> Resolved #90 issue raised

- scholarships.html
I have updated the scholarship cards.
> Scholarship cards Updates Issue Resolved #92

- contact.html
> Co-authored-by: your karthik-kiran-29
<karthikkiran029@gmail.com>
> Co-authored-by: aditya-bhaumik 
<adi.b98120@gmail.com>
result:
I can add the contact us in nav and footer of index.html, feel free to assign to me .
and please give hactoberfest tag too thank you.
https://github.com/aditya-bhaumik/Pathsphere/issues/53
> added contact.html

- jobs.css
- jobs.html
- jobs.js
- styles.css
did everything. added search button that actually works. dynamic job cards.
> Added CSS styles for job listing #55

- styles.css
i have updated the card style in dark mode
> Card Font Updated(#113)

- index.html
- styles.css
Closes: Issue #47 
Title: add scroll to top button
Your Name: Shrishti Singh
Idenitfy yourself: Contributor in gssoc-ext and Hacktoberfest
Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made
I have added the "scroll to top" button to the application. This feature will enhance user navigation, especially on pages with long content, allowing users to easily return to the top without manually scrolling.
> scroll up button added

- script.js
- styles.css
**Description:**
This PR addresses Issue #54, where the task was to add a pop-up effect when buttons are clicked. The following changes were made:
**Button Animation:**
-         Implemented a smooth pop-up effect that triggers when a user clicks on the buttons in the hero section.
-         The animation gives a dynamic and interactive feel to the buttons.
**Changes Made:**
-     Added CSS and JavaScript to create the pop-up effect on button clicks.
-     Ensured smooth transitions and a responsive feel. 
**Related Issue:**
This PR closes #54.
> Co-authored-by: Mohitranag18 <mohitr8998@gmail.com>
> Co-authored-by: aditya-bhaumik <adi.b98120@gmail.com>
> Add Pop-up Effect on Clicking Buttons (#54)

- jobs.css
- jobs.html
- scholarships.html
Make the navbar size same for scholarship  and job potion and also make links visible.please accept my pr request under gssoc-ext level so that i could get gssoc-ext contribution level.
> solved issue #178

- faqs.css
- faqs.html
Reviewed the fix; please check if it is ready to merge.
> Fixed the Dark-Mode Visibility in FAQ Section/Page (issue#146)

- blog.html
- faqs.html
- forum.html
- index.html
- jobs.css
- jobs.html
- scholarships.html
- script.js
- styles.css
make the scroll button avalible on other pages .
> solved issue #191

- about.html
- forum.html
- index.html
- jobs.html
- scholarships.html
- styles.css
**before**
https://github.com/user-attachments/assets/d94623be-0524-4c5c-808e-d639b9dde765
**after**
https://github.com/user-attachments/assets/f5fb94f3-340c-42e7-9284-2dedaf15d64b
**issue #192 **
> adding animation effect in social media icons

- styles.css
##issues solved
**before**
https://github.com/user-attachments/assets/a831e05e-d2cc-4872-a7d6-68e559c4b54c
**after**
https://github.com/user-attachments/assets/cffa93fb-4a1e-4b46-88f7-b195617ef72e
**issues #199 **
> adding hover effect to cards of home page

- scholarships.html
> Resolved the issue of insufficient text brightness in dark mode

- index.html
- styles.css
HELLO @aditya-bhaumik , UPDATED AND FIXED THE NAVBAR ON ALL PAGES AND ALSO MADE IT RESPONSIVE FOR SMALL DEVICES. THIS 
Fixes #217
> NAV BAR ISSUES

- jobs.js
Feature Request: Display "No Jobs Found" Message on Job Listings Page (Issue #179)
I have created a pull request for issue #179 @aditya-bhaumik .. and also added some more job listings. 
Thank you sir!!
> Updated jobs.js

- jobs.css
- jobs.html
Fixes #167 
| Before| After|
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/1b127421-ca0d-47a7-9ee5-81769fef556e)| ![image](https://github.com/user-attachments/assets/67ba8d83-bd87-48f0-b128-0f64baf8ba42)  |
| ![image](https://github.com/user-attachments/assets/0a05a7f3-0c5a-4e26-9146-134c59d7985a)| ![image](https://github.com/user-attachments/assets/57a10169-18f5-411f-b8d1-0c65fb1bf3b7) |
| ![image](https://github.com/user-attachments/assets/d707ce3a-b81e-4322-aefe-0a1d0a82838a)| ![image](https://github.com/user-attachments/assets/8ca76ea9-cc10-4794-b758-d8e7f33142d3)|
> fixed jobs section UI

- styles.css
Apply styling to scroll bar thump and track. And improve the scrolling behaviour.
Fixes #196 
https://github.com/user-attachments/assets/fa7e3c65-a5ef-443d-8844-a0731bba1f1f
https://github.com/user-attachments/assets/268aadd7-15b7-402c-a796-f483fdf6ae12
Has this been tested? (Y)
> Improve Scroll Bar UI (conflict resolve)

- blog.html
- styles.css
Added footer and hero section in the blog page to make similar to the other pages.
Fixes #169
Fixed UI of the blog page to make it look uniform with other pages.
Has this been tested? (Y)
> Added hero section and footer in blog page

- blog.html
- contact.html
- faqs.css
- faqs.html
- forum.html
- jobs.css
- jobs.html
- scholarships.html
- script.js
- styles.css
Closes: #256
FIXED THE RESPONSIVENESS OF THE NAV BAR ON ALL THE PAGES AND ALSO CHANGES THE FONT OF THE TEXT
@aditya-bhaumik
> FIXED THE RESPONSIVENESS ON EVERY PAGE

- styles.css
ISSUE #229 solved here is the before and after 
please give level 2 if possible
> solved the issue of dark mode text invisiblity issue#229 

- .hintrc
- styles.css
Add Hover Effect to the Toggle Mode
Issue Number: #212 
Pls Add Hacktoberfest and gssoc 24-ext under label
> Add Hover Effect to Toggle Mode

- .hintrc
- styles.css
Reverts aditya-bhaumik/Pathsphere#275
> Revert "Add Hover Effect to Toggle Mode"

- blog.html
- faqs.html
- forum.html
- jobs.html
- scholarships.html
- script.js
Closes: #279 
the scroll to top buttons were no longer working and each page had different class names on each button causing even more confusion this PR fixed the scroll to top behavior and standardized the class name according to the class name given for the button in `script.js`
```js
const scrollToTopButton = document.getElementByClassName('scroll-up-btn')[0];
```
this line was added back to the `script.js` file which fixes the broken buttons
all faulty named buttons were fixed with standardized class names so that the script works
None
None
> Issue #279

- blog.html
- faqs.html
- forum.html
- index.html
- jobs.html
- scholarships.html
- styles.css
scroll up button icon was not visible , made it visible
> solved issue #289

- README.md
- styles.css
https://github.com/user-attachments/assets/2d5161b7-b6de-450e-ad28-a0b4db992e31
> Made changes in CSS to fix #294

- scholarships.html
- styles.css
Expected Behavior for Footer Section
Closes: #329
To ensure the footer section is properly positioned and does not overlap with the main content of the scholarship page, enhancing the user experience and overall aesthetics of the site.
Footer Positioning Adjustments:
Changed the footer's position property from fixed to relative, allowing it to naturally flow below the content rather than floating above it.
Padding and Margin Enhancements:
Added bottom padding to the main content area (50px) to create space between the content and the footer.
Increased the padding within the footer to enhance visual appeal and balance the layout.
- [y ] Bugfix (non-breaking change that fixes an issue)
- [ y] My code follows the style …
> Expected Behavior for Footer Section: #329

- index.html
- styles.css
- Updated the navigation links in the index.html file to correctly point to the FAQs page.
- Removed the commented out image content in the features section of index.html.
- Added a button to toggle dark mode in index.html.
- Updated the styles.css file to include a new .copyright class and responsive styles for the features section.
Fixed the Key Feature and Refactor responsive styles for feature section #340
Close - Refactor navigation links and add FAQs page #349
Please provide any other …
> Refactor navigation links and add FAQs page

- pages/blog/blog.css
- pages/blog/blog.html
Closes: #372 
Fix: Newsletter subscription button was not generating an alert after email submission
Added the correct id attribute (subscribe-button) to the newsletter subscription button.
Updated the email input field with the correct id (newsletter-input) to ensure the JavaScript correctly targets the input field.
The alert now correctly triggers upon submission, and the input field is cleared afterward.
- [y ] Bugfix (non-breaking change that fixes an issue)
- [y ] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my own code
- [y ] I have commented my code, particularly in hard-to-understand areas
- [y ] I have made corresponding changes to the documentation
- [y ] My …
> fixed newsletter subscription button functionality

- README.md
Closes: #273
I have added Tech Stach
> Added Tech Stack in README.md

- components/Footer/Footer.html
Closes: #354 
As mentioned in the issue no #354 , I have added the website visitor widget that shows the visitors count
**Before:**
**After:**
@aditya-bhaumik , please assign the respective issue and also please add the gssoc and hacktoberfest labels.
**Please do let me know if the work needs any change or update**
> added website visitors widget #354

- pages/forum/forum.html
- pages/jobs/jobs.html
Closes: #370 
Solve the visibility of the favicon on the form and job section.
This pull request addresses a usability issue by ensuring that favicons are visible on form and job pages. Previously, the incorrect file path was preventing the favicons from displaying correctly, leading to potential confusion for visitors. By updating the file path to the correct location, we have resolved this problem and improved the overall user experience. Visitors can now easily identify the pages they are on and navigate the website more efficiently. This change is essential for enhancing website usability and providing a positive user experience.
This pull request addresses an issue that was preventing favicons from displaying correctly on form and job pages. The previous file path for the favicon was …
> fix the favicon

- index.html
Closes: #388
On hovering the feature names description will be shown and the size of feature names is reduced from 24px to 20px. 
##before
##after
> accordion added

- pages/scholarships/scholarships.css
- pages/scholarships/scholarships.html
- pages/scholarships/scholarships.js
Closes: #149 
#Before: Scholarship listings only displayed basic information (e.g., title, amount, eligibility, deadline) without an option to view  more detailed information.
#Now: Users can click "Read More" to expand the scholarship listing, providing them with further details, enhancing transparency and user experience. Clicking "Read Less" collapses the information back.
This pull request introduces a "Read More" feature for the scholarship listings, allowing users to view additional details about each scholarship. Previously, only basic information was displayed, but now users can expand and collapse more comprehensive details for a better user experience. This enhancement improves the usability of the scholarship page, providing users with easy access to important information …
> Add detailed section(read more) to scholarship cards

- pages/jobs/jobs.js
Closes: #166 
This pull request introduces a live search functionality to the job listings page. Currently, job listings are filtered only after the user clicks the "Search" button. With this update, the job search becomes more dynamic and user-friendly, as results are filtered in real-time based on the user's input.
By adding a keyup event listener to the search input field, users can now see job listings update as they type, making the search process faster and more efficient. The new functionality seamlessly integrates with the existing button-click search, so the previous search method remains intact for users who prefer it.
This pull request adds live search functionality to the job listings page. The live search updates the job listings dynamically as the user types in the search …
> Implemented Live Search Functionality for Job Listings

- components/Footer/Footer.html
- index.html
- pages/blog/blog.css
- pages/jobs/jobs.css
- pages/scholarships/scholarships.css
- styles/styles.css
closes #209 
Improved the mode change functionality on all pages. @aditya-bhaumik @Apoorva57 Please review the PR and merge it accordingly under gssoc-extended and hacktober fest with appropriate level.
> solved issue #209

- index.html
- pages/about/about.html
- pages/blog/blog.html
- pages/contact/contact.html
- pages/faqs/faqs.html
- pages/forum/forum.html
- pages/jobs/jobs.html
- pages/scholarships/scholarships.html
the chatbot is added and its working perfectly.
https://github.com/user-attachments/assets/174f763a-1fc4-4928-8805-731ec316d4f1
> ✨Chatbot added✨

- styles/styles.css
Closes: #455 
footer was not aligned correctly nor it was responsive
before
after
> fixed footer

- pages/blog/blog.css
- pages/blog/blog.html
> I have corrected Sign Up for Newsletters page

- pages/blog/blog.css
- pages/blog/blog.html
- pages/blog/blog.js
Closes: #612 
Implemented a toast-style notification system message for Subscription removing windows Alert
This implementation creates a more professional and modern notification system:
1. It uses a fixed position container for notifications, appearing in the bottom-right corner of the screen.
2. Notifications slide up into view with a smooth animation.
3. Different styles are applied for success and error messages.
4. Each notification includes an icon, message, and close button.
5. Notifications automatically disappear after 3 seconds, or can be manually closed.
6. The system is reusable, allowing you to show different types of notifications throughout your site if needed.
Include any detailed information about …
> Implemented a toast-style notification system message for Subscription removing windows Alert

- pages/scholarship-feature/scholarships.css
Closes: #638 
I made adjustments to the card CSS to improve the layout by adding more padding inside the card, increasing font sizes for readability, and enhancing hover effects for better interaction. This improves the overall user experience.
Improved card layout by adding better padding, increasing font sizes for readability, and refining hover effects for smoother interaction.
I made improvements to the card component styling by:
- Adding more padding inside the card for better spacing and readability.
- Increasing the font size for scholarship names and descriptions.
- Enhancing hover effects to make the user interaction more visually appealing.
- Adjusted button styles to improve overall aesthetics and usability.
- Implemented functionality to dynamically fetch and process an .xlsx …
> enhanced scholarship cards

- README.md
** ADD Roadmap section on README **
Closes: #652 
The documentation for the PathSphere project currently lacks a detailed roadmap section outlining future enhancements and planned features. This absence may lead to confusion among users and contributors regarding upcoming functionalities and project direction. Adding a comprehensive roadmap will help set expectations, attract contributors, and provide users with a clear understanding of the project's growth and development plans.
By outlining specific timelines and milestones, we can enhance the overall clarity and utility of the documentation, fostering a more engaged and informed community around the PathSphere platform.
This pull request adds a roadmap section to the README file of the PathSphere project. The roadmap outlines planned …
> ADD Roadmap section on README

- pages/faqs/faqs.html
Issue resolved: #607
Closes: #(issue number) #607
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
> text corrected

- components/Footer/Footer.html
Closes: #546
Updated the footer to include a dynamic copyright year instead of a static year. The current year is automatically fetched using JavaScript, ensuring that it is always up-to-date.
This pull request addresses issue #546 by implementing a dynamic solution for the copyright year in the footer. It is needed to keep the website content current without manual updates, enhancing user experience.
- Replaced the hardcoded year "2024" with JavaScript code that retrieves the current year.
- Ensured that the footer displays the correct year automatically upon loading the page.
changed system's year
the result's on website
N/A
> copywrite year is dynamic now

- .vscode/settings.json
- pages/faqs/faqs.css
- pages/jobs/jobs.css
- styles/styles.css
Closes: #639 
I’ve successfully made the FAQ, job, and forum pages fully responsive for small screen sizes. Everything is now optimized for better user experience on mobile devices!
This pull request ensuring that the FAQ, job, and forum pages, are optimized for small screen sizes. It improves the user experience on mobile devices by adjusting the layout and content display, making the pages easier to navigate and read. This change is necessary to enhance accessibility and ensure consistency across different devices.
Before:
AFter:
https://github.com/user-attachments/assets/c382e3a9-b032-4f99-a899-e2d4fc086d97
https://github.com/user-attachments/assets/9933076c-b310-4b7e-bb44-ea9903a755be …
> Successfully make faq, job and forum page responsive for small screen sizes.

- components/Footer/Footer.html
- pages/about/about.css
- pages/about/about.html
Closes: #(567)
I have modified the about.html page and applied CSS to enhance its appearance, making it more attractive than before. This includes adding new components such as div and cards, styled with gradients for a more visually appealing look. The About Us page has also been linked in the footer for easier navigation.
This pull request updates the about.html page with a more modern design by introducing gradient-colored divs and cards. These visual improvements align with contemporary web design trends and improve the overall aesthetic appeal of the page.
Enhanced Design: Used gradient backgrounds on cards and sections to improve visual appearance.
Modernized Layout: Applied CSS updates to create a more responsive and user-friendly layout.
Improved Usability: Added a link to the …
> About Us page Added

- pages/forum/forum.css
- pages/forum/forum.html
Closes: #274
**Summary**
This pull request addresses issue #274 by adding responsive card-styled sections and posts to the community discussion section of the forum.
**Details**
- Converted forum-section elements into card format.
- Applied a yellow, white, and grey color theme for consistency with the overall design.
- Implemented a responsive layout using flexbox, where forum-section cards are displayed horizontally and forum-posts are vertically aligned inside each section.
- Added a hover effect to the cards for better interactivity.
- Incorporated media queries to ensure mobile responsiveness, with sections stacking vertically on smaller screens.
New feature (non-breaking change that adds functionality)
**Before:**
**After:**
This PR improves the UI/UX by making the forum's community …
> feat: styled community discussion section with responsive cards

- index.html
- styles/styles.css
This pull request addresses an issue where the star ratings in the testimonials section were displaying vertically on small devices. The following changes were made to ensure the stars align horizontally:
--> Modified the CSS for the star rating elements to utilize flexbox, ensuring proper horizontal alignment across all screen sizes.
--> Adjusted the padding/margin properties to optimize the spacing between stars.
Before editing the code: (The stars in vertical alignment)
After Editing the code: (The stars in horizontal alignment)
> Fix star alignment in testimonials on small devices

- components/Footer/Footer.html
- pages/privacypolicy/privacypolicy.css
- pages/privacypolicy/privacypolicy.html
Closes:  #531
Added privacy policy page to the websote and updated link in the footer for navigation
>  added privacy policy page

- components/Footer/Footer.html
- styles/styles.css
Closes: #688 
This pull request introduces a social sharing feature to the PathSphere platform. Users can now easily share scholarships and job opportunities on popular social media platforms.
Screenshot:
https://github.com/user-attachments/assets/59fbbde7-1ce3-4cab-9361-daa6d0b05514
> added social sharing option

- components/Footer/Footer.html
- pages/contact/contact.css
- pages/contact/contact.html
- pages/contact/contact.js
Closes: #568
This pull request adds a Contact Us page to enhance user interaction by allowing users to easily send their contact details and messages. The page includes a form for capturing the user's name, email, phone number, and message. The design is clean and visually appealing, with proper validation in place to ensure data accuracy before submission. Upon successfully sending the message, the form provides a confirmation message thanking the user and reassuring them that they will be contacted soon.
This pull request adds a Contact Us page with a fully functional and styled form where users can submit their name, email, phone number, and message. It enhances the user experience by making the form visually appealing and responsive using CSS, and adds JavaScript to handle validation …
> Contact us page added

- pages/faqs/faqs.css
- pages/faqs/faqs.html
Closes: #681
Now the FAQ heading is visible in every type of device including mobile view and desktop view.
FAQ heading was present earlier but it was not visible. Now heading is visible which makes the website attractive.
Made changes in the CSS to make the heading visible in every type of device .
Used media queries to make heading visible in mobile view.
> FAQ heading is now visible in every type of device.

- styles/styles.css
Closes: #676 
Added Effects to "Welcome to PathSphere" for better visuals, when we hover it.
before: 
After:
> Adding Effects to "Welcome to PathSphere"

- pages/forum/forum.css
- pages/forum/forum.html
Closes: #issue number : 
#722 
I've changes the user interface of the forum page by enhancing the Ui and adding advanced features
Enhancement of the user interface
#722 
https://github.com/user-attachments/assets/450d5f8c-4f06-47bb-a998-a84890197528
> Changed the user interface of the forum main page

- pages/forum/forum.css
- pages/forum/forum.html
Reverts aditya-bhaumik/Pathsphere#725
> Revert "Changed the user interface of the forum main page"

- pages/blog/blog.html
Closes: #405 
This pull request introduces a new feature that adds a "Visit" button for all scholarship blog posts. Users can now easily navigate to the original scholarship pages by clicking on this button, enhancing the user experience and providing direct access to additional information.
- Implemented a "Visit" button for each blog post displayed on the scholarship page.
- When clicked, the button redirects users to the respective scholarship's official website.
https://github.com/user-attachments/assets/f09aa8fb-407a-4aca-b411-0c687af73d29
> Done adding visit links for all Blogs

- styles/styles.css
#683 
Closes: #683 
I did changes in the background color of feature class  to a little greyish color.This is required so that website can look more attractive and div can be differentiated by the color.
final output
> Updated background color of feature class

- components/Footer/Footer.html
- pages/terms/index.html
- pages/terms/terms.css
- pages/terms/terms.js
Closes: #560 (issue number)
I have created the terms of services page and applied the new changes to the UI also.
The icon issue is resolved and also the UI is updated of terms page accordingly.
> This PR is related to issue #560.Terms and services page created

- pages/scholarship-feature/scholarships.css
Closes: #736
Read whole CSS files.
Made changes to scholarship.css
And now it's done.
> Update scholarships.css #736

- pages/scholarship-feature/scholarships.css
- pages/scholarship-feature/scholarships.html
Closes: #763 
Paging increases the user experience
I have added paging support in scholarship pages
> added paging to scholarships

- styles/styles.css
Closes: #549 
his PR addresses several inconsistencies in the dark mode theme across various components of the application. During testing, it was observed that certain elements did not properly reflect the dark mode styling, leading to a visually inconsistent user experience.
- Updated the color properties for specific elements to ensure they change correctly when the dark mode is activated.
- Corrected the styles for headings and paragraphs within the testimonials section to maintain visual coherence with the overall dark mode theme.
- Ensured that all relevant elements now respond to the dark mode class, providing a seamless and cohesive appearance.
With these changes, users will experience a consistent dark mode theme throughout the application, enhancing readability and aesthetic …
> Fix Theme Inconsistency in Dark Mode

- pages/login-signup/login-signup.html
Closes: #796
The "Name" field on the Sign Up page should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.
Added input validation to the "Name" field
Before 
After
> 🛠️FIX : Sign Up page - Name field validation

- pages/terms/terms.css
Closes: #801 
centers the alignment of title term of service
i commented out the unnecessary margin and added few css properties to enhance.
> fixed title misalignment

- pages/about/about.css
- pages/about/about.html
Closes: #785 
I resolved the issue where the "Our Mission" and "Our Vision" sections were overlapping.
Initially, when I raised the issue, there was a collision between the "Our Mission" and "Our Vision" sections. I have now made the necessary changes, and the overlap between the two sections has been successfully resolved.
In the About Us Page , overlapping between Our Mission and Our Vision section has been successfully resolved.
Before PR :
After PR:
> Resolve the Overlap b/w Our Mission and Our Vision Section #785

- components/Navbar/Navbar.html
- desktop.ini
- styles/styles.css
> closes #710

- pages/login-signup/login-signup.css
- pages/login-signup/login-signup.html
- pages/login-signup/login-signup.js
Closes: #789 
1. Enhances user experience by providing clear feedback on successful registration.
2. Ensures users are properly guided to log in after creating an account.
3. Makes the registration process more interactive and user-friendly without any disruption to the existing functionality.
1. The message automatically disappears after 3 seconds to keep the user interface clean and non-intrusive.
2. JavaScript functionality has been implemented to control the visibility of the success message.
3. The message has a fixed position at the top of the page to ensure visibility, regardless of where the user is scrolling.
- [ X] New feature (non-breaking change that adds functionality)
- [ X] My code follows the style …
> Added Successful msg Upon Registering

- components/Footer/Footer.html
Closes: #617 
working demo:
https://github.com/user-attachments/assets/8e6f57f1-2950-4133-9a20-8be3d5a953bd
> added language translator

- pages/blog/blog.js
Fixes : #817 
implemented the Gmail format validation and display the success message in the middle of the webpage for 3 seconds, 
- [ X] Bugfix (non-breaking change that fixes an issue)
- [ X] My code follows the style guidelines of this project
- [ X] My changes generate no new warnings
- [ X] My changes do not break the current system and pass all existing test cases
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes …
> Successful mailId format checker

- pages/forum/forum.css
- pages/forum/forum.html
- pages/jobs/jobs.html
- pages/jobs/jobs2.css
Closes: #735 
i improve the code of job and forum pages so that they can be responsive on all device size
- [x
https://github.com/user-attachments/assets/18f8d5f2-644c-43fc-893b-c4292b7f060e
-[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> improved job and forum to responsive pages 

- pages/login-signup/login-signup.css
- pages/login-signup/login-signup.html
Fixes #780
Before
https://github.com/user-attachments/assets/3336f254-2bc8-408f-9ef7-6fc2c4364ba8
After
> add icon for login signup Fixes #780

- pages/scholarship-feature/scholarships.css
- pages/scholarship-feature/scholarships.html
- pages/scholarships/scholarships.css
- scripts/componentLoader.js
- styles/styles.css
Enhancing box shadow of DIV's in both Scholarship pages
https://github.com/user-attachments/assets/04207b73-deff-493c-ab4a-6b821bfcc96b
https://github.com/user-attachments/assets/c8636c9e-f4bb-4245-a009-1ef6362a0091
@aditya-bhaumik 
Assign gssoc-ext and Hacktoberfest-accepted label and let me know if any changes required
> Sucessfully enhanced box shadow of DIV's in both Scholarship pages

- README.md
Closes: #851 
This pull request adds the **Table of Contents** section to improve navigation and readability across the project documentation. It also preserves the existing structure, ensuring that no content is removed, but rather enhanced for better user experience.
- Added a **Table of Contents** with links to key sections such as **Important Links**, **Features**, **Future Enhancements**, **Roadmap**, **Tech Stack**, **Contributors**, and **License**.
- Kept the rest of the documentation intact, ensuring that no content under sections like **Features** was altered or removed.
- Improved the visual structure by using consistent heading formats and aligning the ToC with the section headers.
@aditya-bhaumik Please …
> Update README.md with table of contents

- pages/login-signup/login-signup.html
- pages/scholarships/scholarships.html
Closes: #788 
Solve the visibility of the favicon on the login-sign in and scholarship section.
This pull request addresses a usability issue by ensuring that favicons are visible onlogin-sign in and scholarship pages. Previously, the incorrect file path was preventing the favicons from displaying correctly, leading to potential confusion for visitors. By updating the file path to the correct location, we have resolved this problem and improved the overall user experience. Visitors can now easily identify the pages they are on and navigate the website more efficiently. This change is essential for enhancing website usability and providing a positive user experience.
This pull request addresses an issue that was preventing favicons from displaying correctly on login-sign in and scholarship …
> resolve favicons on login-sign in and scholarship

- .vscode/settings.json
- components/Footer/Footer.html
- components/GlobalScripts/GlobalScripts.html
- components/LoadingScreen/LoadingScreen.html
- components/Navbar/Navbar.html
- components/Navbar/Navbar.js
- components/ScrollToTop/ScrollToTop.html
- index.html
- pages/blog/blog.html
- pages/contact/contact.html
- pages/contributor/index.html
- pages/faqs/faqs.html
- pages/forum/forum.html
- pages/jobs/jobs.html
- pages/login-signup/login-signup.html
- pages/login-signup/login-signup.js
- pages/privacypolicy/privacypolicy.html
- pages/resume-builder/resume.html
- pages/scholarship-feature/scholarships.html
- pages/scholarships/scholarships.html
- pages/terms/index.html
- scripts/componentLoader.js
Closes: #886 
there was path issue with loading of image and pages, i fixed it , for all.
Now i am sure that this will work in all the systems. 
The issue with loading images and pages was due to incorrect file paths. After identifying and fixing the path discrepancies, all components are now correctly referenced. The solution ensures that the project will work seamlessly across different systems without path-related errors.
before : localhost stage
after: 
https://github.com/user-attachments/assets/f4675329-976b-4888-8b70-21c564a129a6
dont forget to add gssoc and hacktoberfest tag
> Fixes:#886- Jashwanth/localrun_error

- .vscode/settings.json
- components/Footer/Footer.html
- components/GlobalScripts/GlobalScripts.html
- components/LoadingScreen/LoadingScreen.html
- components/Navbar/Navbar.html
- components/Navbar/Navbar.js
- components/ScrollToTop/ScrollToTop.html
- index.html
- pages/blog/blog.html
- pages/contact/contact.html
- pages/contributor/index.html
- pages/faqs/faqs.html
- pages/forum/forum.html
- pages/jobs/jobs.html
- pages/login-signup/login-signup.html
- pages/login-signup/login-signup.js
- pages/privacypolicy/privacypolicy.html
- pages/resume-builder/resume.html
- pages/scholarship-feature/scholarships.html
- pages/scholarships/scholarships.html
- pages/terms/index.html
- scripts/componentLoader.js
Reverts aditya-bhaumik/Pathsphere#888
> Revert "Fixes:#886- Jashwanth/localrun_error"

- components/Navbar/Navbar.html
- components/Navbar/Navbar.js
- pages/login-signup/login-signup.js
Reverts aditya-bhaumik/Pathsphere#881
> Revert "fix/navigate to home page after successful login"

- index.html
Closes: #886 
https://github.com/user-attachments/assets/eb8d2c27-eb11-48fe-a206-07d1e436dcf9
> Fixes: #886 - jashwanth/final

- components/Navbar/Navbar.html
- pages/blog/blog.html
- pages/blog/write_your_blog.html
Fixes:  #874 
Convert the current static blog page into a dynamic platform that allows for creating and publishing content related to scholarships and job opportunities. This will enable fresh, relevant content and improve user engagement.
Key Specifications:
1. Blog Post Display:
- Renders blog posts dynamically from local storage
- Shows post title, author, date, category, and tags
- Displays a truncated version of the post content
- Includes a "Read More" link for each post
2. Full Post View:
- Opens a modal with the full post content when "Read More" is clicked
- Displays all comments for the post in the modal
3. Commenting System:
- Allows users to add comments to posts
- Displays the latest two comments on the main page
- Shows all comments in the full post view modal
4. Filtering …
> created Own Blog Page

- pages/resume-builder/resume.css
- pages/resume-builder/resume.html
- pages/resume-builder/resume.js
Closes: #880 
- i first fix the background gif which was not working properly.
- fixed the UI
- fixed the bug when we download the resume
- fixed the template issue which there was not functionality 
- added glassmorphism effect  in the bottom features section
Just brushed up the Ui of the Resume builder and fixed the bugs of background and added necessary functionality
- i first fix the background gif which was not working properly.
- fixed the UI
- fixed the bug when we download the resume
- fixed the template issue which there was not functionality 
added two template and made them into buttons which you can click either and choose whichever suites you well.
- added glassmorphism effect  in the bottom features section
- added the adding more education in the education section
_Please …
> Fixed resume page ui and functionality

- pages/resume-builder/resume.css
- pages/resume-builder/resume.html
- pages/resume-builder/resume.js
Reverts aditya-bhaumik/Pathsphere#924
> Revert "Fixed resume page ui and functionality"

- index.html
- resources/resource_library.html
- resources/script.js
- resources/styles.css
Fixes #876
PathSphere Collaborative Resource Library is a centralized platform for sharing and discovering quality educational and career resources. It supports personalized learning, fosters community-driven knowledge sharing and enhances professional development through efficient content curation and accessibility.
1. User Authentication and Role-Based Access
- User login functionality
- Display of logged-in user information
- Role-based access control (admin vs. regular user)
2. Resource Management System
- Display of approved resources in a responsive grid layout
- Resource submission form for users to add new resources
- Categories for resources (Educational Materials, Career Guides, Skill-Building Resources)
- Local storage for saving and loading resources
3. Search and Filter …
> Created Resources Section

- components/Navbar/Navbar.html
- components/Navbar/Navbar.js
Closes: #774 
Dark mode toggle button is successfully implemented and works on all pages
- [X ] Bugfix (non-breaking change that fixes an issue)
- [X ] New feature (non-breaking change that adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] My changes generate no new warnings
- [ X] My changes do not break the current system and pass all existing test cases
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
https://github.com/user-attachments/assets/f8b8a90b-06dc-4138-855c-18 …
> Added dark mode feature

- pages/contact/contact.css
fixed the responsiveness of the contact us page
> fixed the responsiveness of contact us page form

- index.html
- styles/styles.css
- Closes: #865 
This pull request addresses the issue of the cluttered website layout by adding proper spacing and gaps between the sections. The goal is to enhance the visual clarity and improve the overall user experience, making the layout cleaner and more organized.
- Introduced sufficient margins and padding between the website sections.
- Reduced the overcrowded appearance of various elements, making the interface more user-friendly.
- Improved readability by ensuring that content blocks are separated and visually distinct.
- Ensured consistent spacing throughout the website to align with modern UI/UX standards.
- Responsiveness
- UI Consistency
- User Experience
- Accessibility
- Performance
> Enhance Website Layout with Improved Spacing for Visual Clarity!

- index.html
- styles/styles.css
Closes: #887 #896 
Corrected the color under 'Benefits' section the card of 'Resume Builder' and 'Community Forums' which was showing black colored title instead of white colored title and made it responsive so that elements don't overflow
> corrected title color and made it responsive for smaller screens

- pages/scholarship-feature/scholarships.css
- pages/scholarship-feature/scholarships.html
Closes: #885 
"This PR resolves the issue of static backgrounds on the scholarship page by adding a wallpaper rotation feature. Users will enjoy a refreshing experience with changing backgrounds, making the page more visually appealing and engaging."
- [x
https://github.com/user-attachments/assets/4d3803c3-13e6-4069-9b74-ae059faab086
] New and existing unit tests pass locally with my changes
> Changing Backgrounds to Scholarship Page for Improved User Experience

- pages/login-signup/login-signup.css
- pages/login-signup/login-signup.html
Closes: #978 
To add buttons for Google, Facebook, and X (formerly Twitter) to your website or app,
https://github.com/user-attachments/assets/c05e7195-a184-43c5-9c2b-f4f60290de16
- [ X] Bugfix (non-breaking change that fixes an issue)
- [ X] New feature (non-breaking change that adds functionality)
- [ X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X] My code follows the style guidelines of this project
- [ X] My changes generate no new warnings
- [X ] My changes do not break …
>  add button like google and facbook

- README.md
This pull request introduces several enhancements and corrections to the PathSphere readme. The changes are aimed at improving the overall user experience and ensuring that the documentation is accurate and informative.
1. **Corrected SVG Typo**: Fixed a typo in the SVG content for improved rendering and consistency.
2. Did basic formatting
3. **Added Table for Language Section**: Implemented a structured table format in the language section to enhance readability and organization.
4. **Rainbow Line**: Introduced a visually appealing rainbow line for better separation of content sections.
5. **Strangers Over Time**: Included a new feature to display "strangers over time" effectively.
6. **Automatic Scrolling Contributors**: Implemented automatic scrolling for the contributors section to …
> Enhancements and Corrections to PathSphere README.md

- index.html
- styles/styles.css
Closes: #896 
by mistakenly i added some issues
> title of card

- index.html
Reverts aditya-bhaumik/Pathsphere#1005
> Revert "Aligned the items of the forum"

- pages/blog/blog.css
- pages/blog/blog.html
Closes: #931 
This PR enhances the blog section by implementing a carousel layout for blog cards, adding pagination controls with arrows for seamless navigation, hover effects on key elements, and a copy link button with a notification effect.
Enhancing the blog section’s user experience, this PR implements a carousel format for easier browsing, pagination for navigating through multiple pages, interactive hover effects for better visual feedback, and a copy link button with a confirmation notification. These updates aim to improve user interaction and streamline access to blog content.
- Carousel Setup: Utilized a carousel structure to display blog cards in a sliding format. The design ensures responsive display across devices.
- Pagination Controls: Added pagination buttons to switch …
> [UI] Redesign of blogs section

- index.html
- pages/faqs/faqs.css
- pages/faqs/faqs.html
Closes: #982 
As described in the issue, I made the following improvements to the FAQ section UI:
Enhanced the visual appeal of the FAQ section.
Adjusted the UI of the questions to make them more readable.
Added a "Drop Your Query" section, where users can submit questions related to the website.
Additionally, I noticed alignment issues on the Pathspare homepage, which I corrected to improve layout consistency.
The attached video demonstrates these updates and compares them to the design on the live Pathspare 
- [x
https://github.com/user-attachments/assets/fab1c79b-3349-45e8-966a-8753f48eea8f
] New and existing unit tests pass locally with my …
> Enhanced FAQ Section and Homepage Alignment Fixes

- pages/contact/contact.css
- pages/contact/contact.html
Closes: #1020 
This pull request enhances the "Contact Us" page by integrating four Google Maps, representing our key locations: Delhi, Bangalore, Hyderabad, and Mumbai. The maps are organized in a responsive layout, with four  maps  providing users with easy access to our locations.
###Details
1. Added a new section titled "Our Locations" to the "Contact Us" page.
2. Implemented four Google Maps using <iframe> elements for each city.
3. Utilized a flexbox layout for responsive design, ensuring proper alignment and spacing of the maps.
###Summary 
1. Verified that all maps load correctly and are responsive on various screen sizes.
2. Ensured that the contact form and existing functionalities remain unaffected. …
> Add Location Maps to Contact Us Page

- pages/contact/contact.css
- pages/contact/contact.html
- pages/contact/contact.js
Closes: #827 
The contact form has now proper validation to each field which prevents faulty submissions from user
- [X ] New feature (non-breaking change that adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] My changes generate no new warnings
- [ X] My changes do not break the current system and pass all existing test cases
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
> Add contact form validation and update error message

- pages/jobs/jobs2.css
Closes: #951 
The images displayed in the carousel appear smaller and less vibrant than expected, negatively impacting the overall visual appeal.
Images in the carousel should be displayed in their original size and resolution, maintaining their vibrant colors and clarity.
> 🛠️Fix :Carousel Images Appear Diminished/Lessened, Affecting Visual Quality

- components/Navbar/Navbar.html
Fixes #1042 
The navbar’s mobile view alignment and spacing have been optimized to ensure a clean, user-friendly experience across all mobile screen sizes.
It;s been optimized by adjusting padding and margins, creating a more compact, balanced layout. This enhances visual appeal and ease of navigation on small screens. Additional media queries for smaller mobile screens were added, reducing padding, font size, and gaps between elements. 
https://github.com/user-attachments/assets/c15ef8a3-4d72-4ea4-a58c-c9bfc6794929
Kindly review my PR and merge it @aditya-bhaumik , @Apoorva57 .
> Enhanced navbar for mobile view

- pages/scholarship-feature/scholarships.css
Issue resolved: #935
Closes: #(issue number)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
> text color changed

- pages/login-signup/login-signup.html
- pages/login-signup/login-signup.js
I have resolved the issue of not navigating to the home page after the login is done
Closes: #944 
Now if the user is registered succesfully and if the user is giving correct credential in login page user is able to navigate to home page
- [X ] Bugfix (non-breaking change that fixes an issue)
- [ X] My code follows the style guidelines of this project
- [X ] My changes generate no new warnings
- [ X] My changes do not break the current system and pass all existing test cases
- [ X] I have added tests that prove my fix is effective …
> Issue #944 Navigating issue even if the user is logged in to website

- pages/login-signup/login-signup.css
- pages/login-signup/login-signup.js
Fixes #1044 
Someone already solved the redirecting to x login page issue , so i enhanced the login-signup form input boxes , which looks more appealing when clicked to fill details.
Kindly review and merge my PR
> Enhanced the input boxes

- components/Footer/Footer.html
- styles/styles.css
Closes: #712 
This pull request aims to enhance the visual appeal of the social media icons on the website by redesigning them and adding subtle animations to create a more engaging user experience.
- Redesigned social media icons for a cleaner and more modern look.
- Implemented smooth hover animations to draw attention to the icons.
- Optimized the icon sizes and spacing for better visual balance.
- Ensured cross-browser compatibility and responsiveness for optimal display on various devices.
- Updated the iconography to align with the latest design trends.
- Improved color contrast for better visibility.
- Adjusted the icon size and spacing for a more consistent and visually pleasing layout.
- Added a subtle hover effect, such as a color change when hover over icons.
- Optimized the …
> improve social media icons

- pages/jobs/jobs.html
Closes: #849 
I have made it appealing and professional and have done a new fork so solve the issues we were facing.
It is now professionally designed for a job portal standard.
> I have designed a nicer and better search bar

- components/Footer/Footer.html
- styles/styles.css
Closes: #1064 (issue number)
I have  made some changes in the footer section and fixed the alignment issues.
before
after
> #1064 Alignment Issues and Footer Design Improvements Needed

- pages/forum/forum.html
- pages/jobs/jobs.html
- pages/jobs/jobs2.css
- styles/styles.css
Closes: #1094 
Change the theme on the forum page and Jobs page which is not updating when switching to dark mode. Ensure the background, text, and other UI elements adapt properly to match the dark theme styling.
> Change Background color on Dark Mode

- components/Navbar/Navbar.html
- index.html
- styles/styles.css
#1088 
- Changes the look of the navigation bar to improve aesthetics and usability.
- Adds color to the sidebar button for mobile devices, enhancing visibility and user experience.
- Applies a new font style to give the application a modern and cohesive look.
> update nav style

- pages/forum/forum.css
- styles/styles.css
Closes: #1132
fixes the visibility issue in forum section
this pull request corrects the visibilty of the text in dark mode and make it readable to the user 
firstly i changed the color of anchor tags text to black which looks much better than before .
secondly to make it readable in dark mode i made some changes in style.css by : [ .darkmode .replies {color:white;} ] 
BEFORE:
AFTER:
The above screenshots depict that the problem has been solved succesfully .
> bug : Fixes the visibility issue in forum section

- styles/styles.css
Closes: #1065 
Fixes #1065 must be included in the description.
Process completed with exit code 1.
i fixed the text visibility issue and also fixed css file .
> #1065 Text Visibility Issue in Scholarship Options 

- pages/scholarship-feature/scholarships.css
- pages/scholarship-feature/scholarships.html
Summary
Closes : #1067
Fixes #1067
I have improve the css of scholarship section adjust inner images and text and also update test area
I have improve the css of scholarship section adjust inner images and text and also update test area
Before :
After : 
> Resolve issue of scholarship section

- styles/styles.css
Closes: #1109 
the text is adjusted in the dark mode
this enables the users in positive manner
Its very essential since it enables the users readability
- [ X] Bugfix (non-breaking change that fixes an issue)
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My changes generate no new warnings
- [X ] My changes do not break the current system and pass all existing test …
> TEXT IS INVISIBLE IN THE DARK MODE(fixes #1109)

- components/ScrollToTop/ScrollToTop.css
- components/ScrollToTop/ScrollToTop.html
- index.html
- pages/blog/blog.html
- pages/faqs/faqs.html
- pages/forum/forum.html
- pages/jobs/jobs.html
- pages/scholarship-feature/scholarships.html
- pages/scholarships/scholarships.html
Enhanced scroll back button with timeline on it for smoother functioning.
##description
Added Enhanced scroll back button with timeline on it for smoother functioning to ALL pages. 
Closes: #1160
https://github.com/user-attachments/assets/852596c1-f518-4dff-ad88-ae5c3b7034b8
> Added Enhanced scroll back button with timeline on it for smoother functioning to ALL pages.
